# Generated by Django 4.1.6 on 2023-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_todo_date_todo_alter_todo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='state_id',
            field=models.IntegerField(default=0, verbose_name='Состояние Id'),
        ),
    ]
