# Generated by Django 4.1.6 on 2023-02-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_todo_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='state_id',
        ),
    ]
